FROM ubuntu:14.10
MAINTAINER Greg Gigon <greg.gigon@somemail.com>

RUN apt-get update && apt-get -y install wget python2.7 ipython zip unzip vim nano && apt-get clean \
	 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

