#!/bin/bash

docker run -d -v /opt/registry-storage:/registry -e STORAGE_PATH=/registry -e STORAGE_BACKEND=sqlalchemy \
			-e SETTINGS_FLAVOR=local -p 5000:5000 --name docker_registry registry

sleep 5s

docker run -d -e ENV_DOCKER_REGISTRY_HOST=registry -e ENV_DOCKER_REGISTRY_PORT=5000 -p 5005:80 --name docker_registry_frontend \
 			--link docker_registry:registry konradkleine/docker-registry-frontend