VAGRANTFILE_API_VERSION="2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  openshift_version = "v0.4.1"

  config.vm.box = "MintAll"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "DeepHack Mint"
    vb.memory = 2024
    vb.cpus = 2
    vb.gui = true
    vb.customize [
      "modifyvm", :id,
      "--groups", "/Hack Night"
    ]
  end

  # IP configuration
  master_ip = "10.245.2.2"

  config.vm.define "master" do |master| 
    master.vm.hostname = "master"

    master.vm.network "private_network", ip: "#{master_ip}"

    master.vm.network "forwarded_port", guest: 80, host: 1080
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.network "forwarded_port", guest: 8443, host: 8443
    master.vm.network "forwarded_port", guest: 8444, host: 8444
    master.vm.network "forwarded_port", guest: 9080, host: 9080
  end

  config.vm.provision :shell, path: "bootstrap.sh", args: [openshift_version]
  config.vm.provision :shell, path: "master.sh", args: [master_ip, openshift_version]
  config.vm.provision :shell, path: "prepare-documentation.sh"
  config.vm.provision :shell, path: "clean_box.sh"

end
